//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.GorVodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Employee.
    /// </summary>
    // *** Start programmer edit section *** (Employee CustomAttributes)

    // *** End programmer edit section *** (Employee CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EmployeeE", new string[] {
            "FIO as \'FIO\'",
            "email as \'Email\'",
            "Active as \'Active\'"})]
    [View("EmployeeL", new string[] {
            "FIO as \'FIO\'",
            "email as \'Email\'",
            "Active as \'Active\'"})]
    public class Employee : IIS.GorVodokanal.Dictionary
    {
        
        private string fFIO;
        
        private string femail;
        
        // *** Start programmer edit section *** (Employee CustomMembers)

        // *** End programmer edit section *** (Employee CustomMembers)

        
        /// <summary>
        /// FIO.
        /// </summary>
        // *** Start programmer edit section *** (Employee.FIO CustomAttributes)

        // *** End programmer edit section *** (Employee.FIO CustomAttributes)
        [StrLen(255)]
        public virtual string FIO
        {
            get
            {
                // *** Start programmer edit section *** (Employee.FIO Get start)

                // *** End programmer edit section *** (Employee.FIO Get start)
                string result = this.fFIO;
                // *** Start programmer edit section *** (Employee.FIO Get end)

                // *** End programmer edit section *** (Employee.FIO Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.FIO Set start)

                // *** End programmer edit section *** (Employee.FIO Set start)
                this.fFIO = value;
                // *** Start programmer edit section *** (Employee.FIO Set end)

                // *** End programmer edit section *** (Employee.FIO Set end)
            }
        }
        
        /// <summary>
        /// email.
        /// </summary>
        // *** Start programmer edit section *** (Employee.email CustomAttributes)

        // *** End programmer edit section *** (Employee.email CustomAttributes)
        [StrLen(255)]
        public virtual string email
        {
            get
            {
                // *** Start programmer edit section *** (Employee.email Get start)

                // *** End programmer edit section *** (Employee.email Get start)
                string result = this.femail;
                // *** Start programmer edit section *** (Employee.email Get end)

                // *** End programmer edit section *** (Employee.email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Employee.email Set start)

                // *** End programmer edit section *** (Employee.email Set start)
                this.femail = value;
                // *** Start programmer edit section *** (Employee.email Set end)

                // *** End programmer edit section *** (Employee.email Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EmployeeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeE", typeof(IIS.GorVodokanal.Employee));
                }
            }
            
            /// <summary>
            /// "EmployeeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EmployeeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EmployeeL", typeof(IIS.GorVodokanal.Employee));
                }
            }
        }
    }
}
