//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.GorVodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request.
    /// </summary>
    // *** Start programmer edit section *** (RequestFromUser CustomAttributes)

    // *** End programmer edit section *** (RequestFromUser CustomAttributes)
    [AutoAltered()]
    [Caption("Обращение")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RequestE", new string[] {
            "Number as \'Number\'",
            "Status as \'Status\'",
            "DateOpen as \'Date open\'",
            "Applicant as \'Applicant\'",
            "DateClose as \'Date close\'",
            "Responsible as \'Responsible\'",
            "Responsible.FIO as \'FIO\'",
            "SecondaryRequest as \'Secondary Request\'",
            "SecondaryRequest.Applicant as \'Applicant\'",
            "RequestType as \'Request type\'",
            "RequestType.Name as \'Name\'",
            "RequestKind as \'Request kind\'",
            "RequestKind.Name as \'Name\'",
            "Operator as \'Operator\'",
            "Operator.FIO as \'FIO\'",
            "RequestCause as \'Request cause\'",
            "RequestCause.Name as \'Name\'"})]
    [MasterViewDefineAttribute("RequestE", "Responsible", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FIO")]
    [MasterViewDefineAttribute("RequestE", "SecondaryRequest", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Applicant")]
    [MasterViewDefineAttribute("RequestE", "RequestType", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("RequestE", "RequestKind", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("RequestE", "Operator", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FIO")]
    [MasterViewDefineAttribute("RequestE", "RequestCause", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("RequestL", new string[] {
            "Number as \'Number\'",
            "Status as \'Status\'",
            "DateOpen as \'Date open\'",
            "Applicant as \'Applicant\'",
            "DateClose as \'Date close\'",
            "Responsible as \'FIO\'",
            "SecondaryRequest.Applicant as \'Applicant\'",
            "RequestType as \'Name\'",
            "RequestKind as \'Name\'",
            "Operator as \'FIO\'",
            "RequestCause as \'Name\'"}, Hidden=new string[] {
            "Responsible",
            "RequestType",
            "RequestKind",
            "Operator",
            "RequestCause"})]
    public class RequestFromUser : ICSSoft.STORMNET.DataObject
    {
        
        private int fNumber;
        
        private IIS.GorVodokanal.tStatus fStatus;
        
        private string fApplicant;
        
        private System.DateTime fDateOpen;
        
        private System.DateTime fDateClose;
        
        private IIS.GorVodokanal.Employee fOperator;
        
        private IIS.GorVodokanal.RequestCause fRequestCause;
        
        private IIS.GorVodokanal.RequestKind fRequestKind;
        
        private IIS.GorVodokanal.RequestType fRequestType;
        
        private IIS.GorVodokanal.Employee fResponsible;
        
        private IIS.GorVodokanal.RequestFromUser fSecondaryRequest;
        
        // *** Start programmer edit section *** (RequestFromUser CustomMembers)

        // *** End programmer edit section *** (RequestFromUser CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.Number CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.Number Get start)

                // *** End programmer edit section *** (RequestFromUser.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (RequestFromUser.Number Get end)

                // *** End programmer edit section *** (RequestFromUser.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.Number Set start)

                // *** End programmer edit section *** (RequestFromUser.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (RequestFromUser.Number Set end)

                // *** End programmer edit section *** (RequestFromUser.Number Set end)
            }
        }
        
        /// <summary>
        /// Status.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.Status CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.Status CustomAttributes)
        public virtual IIS.GorVodokanal.tStatus Status
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.Status Get start)

                // *** End programmer edit section *** (RequestFromUser.Status Get start)
                IIS.GorVodokanal.tStatus result = this.fStatus;
                // *** Start programmer edit section *** (RequestFromUser.Status Get end)

                // *** End programmer edit section *** (RequestFromUser.Status Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.Status Set start)

                // *** End programmer edit section *** (RequestFromUser.Status Set start)
                this.fStatus = value;
                // *** Start programmer edit section *** (RequestFromUser.Status Set end)

                // *** End programmer edit section *** (RequestFromUser.Status Set end)
            }
        }
        
        /// <summary>
        /// Applicant.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.Applicant CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.Applicant CustomAttributes)
        [StrLen(255)]
        public virtual string Applicant
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.Applicant Get start)

                // *** End programmer edit section *** (RequestFromUser.Applicant Get start)
                string result = this.fApplicant;
                // *** Start programmer edit section *** (RequestFromUser.Applicant Get end)

                // *** End programmer edit section *** (RequestFromUser.Applicant Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.Applicant Set start)

                // *** End programmer edit section *** (RequestFromUser.Applicant Set start)
                this.fApplicant = value;
                // *** Start programmer edit section *** (RequestFromUser.Applicant Set end)

                // *** End programmer edit section *** (RequestFromUser.Applicant Set end)
            }
        }
        
        /// <summary>
        /// DateOpen.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.DateOpen CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.DateOpen CustomAttributes)
        public virtual System.DateTime DateOpen
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.DateOpen Get start)

                // *** End programmer edit section *** (RequestFromUser.DateOpen Get start)
                System.DateTime result = this.fDateOpen;
                // *** Start programmer edit section *** (RequestFromUser.DateOpen Get end)

                // *** End programmer edit section *** (RequestFromUser.DateOpen Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.DateOpen Set start)

                // *** End programmer edit section *** (RequestFromUser.DateOpen Set start)
                this.fDateOpen = value;
                // *** Start programmer edit section *** (RequestFromUser.DateOpen Set end)

                // *** End programmer edit section *** (RequestFromUser.DateOpen Set end)
            }
        }
        
        /// <summary>
        /// DateClose.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.DateClose CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.DateClose CustomAttributes)
        public virtual System.DateTime DateClose
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.DateClose Get start)

                // *** End programmer edit section *** (RequestFromUser.DateClose Get start)
                System.DateTime result = this.fDateClose;
                // *** Start programmer edit section *** (RequestFromUser.DateClose Get end)

                // *** End programmer edit section *** (RequestFromUser.DateClose Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.DateClose Set start)

                // *** End programmer edit section *** (RequestFromUser.DateClose Set start)
                this.fDateClose = value;
                // *** Start programmer edit section *** (RequestFromUser.DateClose Set end)

                // *** End programmer edit section *** (RequestFromUser.DateClose Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.Operator CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.Operator CustomAttributes)
        [NotNull()]
        public virtual IIS.GorVodokanal.Employee Operator
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.Operator Get start)

                // *** End programmer edit section *** (RequestFromUser.Operator Get start)
                IIS.GorVodokanal.Employee result = this.fOperator;
                // *** Start programmer edit section *** (RequestFromUser.Operator Get end)

                // *** End programmer edit section *** (RequestFromUser.Operator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.Operator Set start)

                // *** End programmer edit section *** (RequestFromUser.Operator Set start)
                this.fOperator = value;
                // *** Start programmer edit section *** (RequestFromUser.Operator Set end)

                // *** End programmer edit section *** (RequestFromUser.Operator Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.RequestCause CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.RequestCause CustomAttributes)
        [NotNull()]
        public virtual IIS.GorVodokanal.RequestCause RequestCause
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.RequestCause Get start)

                // *** End programmer edit section *** (RequestFromUser.RequestCause Get start)
                IIS.GorVodokanal.RequestCause result = this.fRequestCause;
                // *** Start programmer edit section *** (RequestFromUser.RequestCause Get end)

                // *** End programmer edit section *** (RequestFromUser.RequestCause Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.RequestCause Set start)

                // *** End programmer edit section *** (RequestFromUser.RequestCause Set start)
                this.fRequestCause = value;
                // *** Start programmer edit section *** (RequestFromUser.RequestCause Set end)

                // *** End programmer edit section *** (RequestFromUser.RequestCause Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.RequestKind CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.RequestKind CustomAttributes)
        [NotNull()]
        public virtual IIS.GorVodokanal.RequestKind RequestKind
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.RequestKind Get start)

                // *** End programmer edit section *** (RequestFromUser.RequestKind Get start)
                IIS.GorVodokanal.RequestKind result = this.fRequestKind;
                // *** Start programmer edit section *** (RequestFromUser.RequestKind Get end)

                // *** End programmer edit section *** (RequestFromUser.RequestKind Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.RequestKind Set start)

                // *** End programmer edit section *** (RequestFromUser.RequestKind Set start)
                this.fRequestKind = value;
                // *** Start programmer edit section *** (RequestFromUser.RequestKind Set end)

                // *** End programmer edit section *** (RequestFromUser.RequestKind Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.RequestType CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.RequestType CustomAttributes)
        [NotNull()]
        public virtual IIS.GorVodokanal.RequestType RequestType
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.RequestType Get start)

                // *** End programmer edit section *** (RequestFromUser.RequestType Get start)
                IIS.GorVodokanal.RequestType result = this.fRequestType;
                // *** Start programmer edit section *** (RequestFromUser.RequestType Get end)

                // *** End programmer edit section *** (RequestFromUser.RequestType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.RequestType Set start)

                // *** End programmer edit section *** (RequestFromUser.RequestType Set start)
                this.fRequestType = value;
                // *** Start programmer edit section *** (RequestFromUser.RequestType Set end)

                // *** End programmer edit section *** (RequestFromUser.RequestType Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.Responsible CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.Responsible CustomAttributes)
        public virtual IIS.GorVodokanal.Employee Responsible
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.Responsible Get start)

                // *** End programmer edit section *** (RequestFromUser.Responsible Get start)
                IIS.GorVodokanal.Employee result = this.fResponsible;
                // *** Start programmer edit section *** (RequestFromUser.Responsible Get end)

                // *** End programmer edit section *** (RequestFromUser.Responsible Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.Responsible Set start)

                // *** End programmer edit section *** (RequestFromUser.Responsible Set start)
                this.fResponsible = value;
                // *** Start programmer edit section *** (RequestFromUser.Responsible Set end)

                // *** End programmer edit section *** (RequestFromUser.Responsible Set end)
            }
        }
        
        /// <summary>
        /// Request.
        /// </summary>
        // *** Start programmer edit section *** (RequestFromUser.SecondaryRequest CustomAttributes)

        // *** End programmer edit section *** (RequestFromUser.SecondaryRequest CustomAttributes)
        public virtual IIS.GorVodokanal.RequestFromUser SecondaryRequest
        {
            get
            {
                // *** Start programmer edit section *** (RequestFromUser.SecondaryRequest Get start)

                // *** End programmer edit section *** (RequestFromUser.SecondaryRequest Get start)
                IIS.GorVodokanal.RequestFromUser result = this.fSecondaryRequest;
                // *** Start programmer edit section *** (RequestFromUser.SecondaryRequest Get end)

                // *** End programmer edit section *** (RequestFromUser.SecondaryRequest Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestFromUser.SecondaryRequest Set start)

                // *** End programmer edit section *** (RequestFromUser.SecondaryRequest Set start)
                this.fSecondaryRequest = value;
                // *** Start programmer edit section *** (RequestFromUser.SecondaryRequest Set end)

                // *** End programmer edit section *** (RequestFromUser.SecondaryRequest Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestE", typeof(IIS.GorVodokanal.RequestFromUser));
                }
            }
            
            /// <summary>
            /// "RequestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestL", typeof(IIS.GorVodokanal.RequestFromUser));
                }
            }
        }
    }
}
