//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.GorVodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Request cause.
    /// </summary>
    // *** Start programmer edit section *** (RequestCause CustomAttributes)

    // *** End programmer edit section *** (RequestCause CustomAttributes)
    [AutoAltered()]
    [Caption("Request cause")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RequestCauseE", new string[] {
            "Name as \'Name\'",
            "Code as \'Code\'",
            "Active as \'Active\'"})]
    [View("RequestCauseL", new string[] {
            "Name as \'Name\'",
            "Code as \'Code\'",
            "Active as \'Active\'"})]
    public class RequestCause : IIS.GorVodokanal.Dictionary
    {
        
        private string fName;
        
        private int fCode;
        
        // *** Start programmer edit section *** (RequestCause CustomMembers)

        // *** End programmer edit section *** (RequestCause CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (RequestCause.Name CustomAttributes)

        // *** End programmer edit section *** (RequestCause.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (RequestCause.Name Get start)

                // *** End programmer edit section *** (RequestCause.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (RequestCause.Name Get end)

                // *** End programmer edit section *** (RequestCause.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestCause.Name Set start)

                // *** End programmer edit section *** (RequestCause.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (RequestCause.Name Set end)

                // *** End programmer edit section *** (RequestCause.Name Set end)
            }
        }
        
        /// <summary>
        /// Code.
        /// </summary>
        // *** Start programmer edit section *** (RequestCause.Code CustomAttributes)

        // *** End programmer edit section *** (RequestCause.Code CustomAttributes)
        public virtual int Code
        {
            get
            {
                // *** Start programmer edit section *** (RequestCause.Code Get start)

                // *** End programmer edit section *** (RequestCause.Code Get start)
                int result = this.fCode;
                // *** Start programmer edit section *** (RequestCause.Code Get end)

                // *** End programmer edit section *** (RequestCause.Code Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RequestCause.Code Set start)

                // *** End programmer edit section *** (RequestCause.Code Set start)
                this.fCode = value;
                // *** Start programmer edit section *** (RequestCause.Code Set end)

                // *** End programmer edit section *** (RequestCause.Code Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RequestCauseE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestCauseE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestCauseE", typeof(IIS.GorVodokanal.RequestCause));
                }
            }
            
            /// <summary>
            /// "RequestCauseL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RequestCauseL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RequestCauseL", typeof(IIS.GorVodokanal.RequestCause));
                }
            }
        }
    }
}
