//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.GorVodokanal
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T status.
    /// </summary>
    // *** Start programmer edit section *** (tStatus CustomAttributes)

    // *** End programmer edit section *** (tStatus CustomAttributes)
    public enum tStatus
    {
        
        // *** Start programmer edit section *** (tStatus.Opened CustomAttributes)

        // *** End programmer edit section *** (tStatus.Opened CustomAttributes)
        [Caption("Открыто")]
        Opened,
        
        // *** Start programmer edit section *** (tStatus.Controlling CustomAttributes)

        // *** End programmer edit section *** (tStatus.Controlling CustomAttributes)
        [Caption("На контроле")]
        Controlling,
        
        // *** Start programmer edit section *** (tStatus.Attached CustomAttributes)

        // *** End programmer edit section *** (tStatus.Attached CustomAttributes)
        [Caption("Присоединено")]
        Attached,
        
        // *** Start programmer edit section *** (tStatus.Closed CustomAttributes)

        // *** End programmer edit section *** (tStatus.Closed CustomAttributes)
        [Caption("Закрыто")]
        Closed,
    }
}
